Fixed race condition

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,4 +37,41 @@ jobs:
             changed_plugins=$(git diff --name-only $last_release ./plugins)
             for i in $changed_plugins ; do 
               if [ ! -f "$i" ] ; then
-               
+                continue
+              fi
+
+              id=$(basename $i | cut -d '.' -f 1)
+              payload="$(jq -Rs "{contents: ., type: \"${id}\"}" $i)"
+              status=$(curl \
+                -H "x-selectstar-secret: $X_SELECTSTAR_SECRET" \
+                -X POST \
+                -d "$payload" \
+                -o /tmp/output.json \
+                -w  "%{http_code}" \
+                https://stanza-source-service-enle4clm4a-ue.a.run.app/plugins )
+              if [ "$status" != "200" ] ; then 
+                echo "Plugin $id failed with status $status" 
+                cat /tmp/output.json
+                exit 1
+              fi
+            done
+
+workflows:
+  version: 2
+  release:
+    jobs: 
+      - publish_sources:
+          filters:
+            branches:
+              ignore: /.*/
+            tags:
+              only: /^v\d+\.\d+\.\d+.*/
+
+      - publish-github-release:
+          requires:
+            - publish_sources
+          filters:
+            branches:
+              ignore: /.*/
+            tags:
+              only: /^v\d+\.\d+\.\d+.*/
